apiVersion: apps/v1
kind: Deployment
metadata:
  name: students
  namespace: production
  labels:
    app: students
spec:
  replicas: 1
  selector:
    matchLabels:
      app: students
  template:
    metadata:
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
      labels:
        app: students
        hostname: students
    spec:
      hostname: students
      dnsPolicy: Default
      dnsConfig:
        searches:
          - cs.calvin.edu
      containers:
      - name: students
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ default "latest" .Values.image.tag }}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m" #0.1 CPU
          limits:
            memory: "200Mi"
            cpu: "250m" #0.25 CPU
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 15
        volumeMounts:
        - mountPath: /home
          name: mount0
          readOnly: true
      volumes:
      - name: mount0
        nfs:
          path: /export/home
          server: aznfs-int.cs.calvin.edu
---
apiVersion: v1
kind: Service
metadata:
  name: students
  namespace: production
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: students
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: students-{{ default "staging" .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: students
  minReplicas: 1
  maxReplicas: 4
  #targetCPUUtilizationPercentage: 80
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85

